export const tones = {
    a: "Alterous.",
    ay: "At you.",
    c: "Copypasta.",
    cb: "Clickbait.",
    f: "Fake.",
    g: "Genuine / Genuine question.",
    gen: "Genuine / Genuine question.",
    genq: "Genuine / Genuine question.",
    hj: "Half joking.",
    hsrs: "Half serious.",
    hyp: "Hyperbole.",
    ij: "Inside joke.",
    j: "Joking.",
    l: "Lyrics.",
    lh: "Light hearted.",
    li: "Literal / Literally.",
    lu: "A little upset.",
    ly: "Lyrics.",
    m: "Metaphor / Metaphorically.",
    nay: "Not at you.",
    nbh: "Nobody here.",
    nbr: "Not being rude.",
    nc: "Negative connotation.",
    neg: "Negative connotation.",
    neu: "Neutral / Neutral connotation.",
    nf: "Not forced.",
    nm: "Not mad.",
    ns: "Non-sexual intent.",
    nsb: "Not subtweeting.",
    nsrs: "Not serious.",
    nsx: "Non-sexual intent.",
    ot: "Off topic.",
    p: "Platonic.",
    pc: "Positive connotation.",
    pos: "Positive connotation.",
    q: "Quote.",
    r: "Romantic.",
    ref: "Reference.",
    rh: "Rhetorical question.",
    rt: "Rhetorical question.",
    s: "Sarcastic / Sarcasm.",
    sarc: "Sarcastic / Sarcasm.",
    srs: "Serious.",
    sx: "Sexual intent.",
    t: "Teasing.",
    th: "Threat.",
    x: "Sexual intent."
}
